import 'package:http/http.dart' as http;
import 'dart:convert';

class FilterMe {

  Future<List<dynamic>> filter(String qry) async {
    final url = 'http://osamaadel.pythonanywhere.com/filter?query=$qry';
    try {
      final response = await http.get(url);
      final extractedData = json.decode(response.body) as Map<String, dynamic>;
      if (extractedData == null) {
        return null;
      }
      //final List<String> loadedHadithes = [];
      //print(extractedData);

      return extractedData['filter'];
      // return extractedData['Tfidf'];
    } catch (error) {
      throw (error);
    }
  }
  static const List heads = [
    'Belief - كتاب الإيمان',
    'Virtues of Prayer at Masjid Makkah and Madinah - كتاب فضل الصلاة فى مسجد مكة والمدينة',
    'The Book Pertaining to the Rules of Inheritance - كتاب الفرائض',
    'The Book on Sacrifices - كتاب الأضاحى عن رسول الله صلى الله عليه وسلم',
    'The Book Pertaining to the Turmoil and Portents of the Last Hour - كتاب الفتن وأشراط الساعة',
    'Virtues and Merits of the Prophet (pbuh) and his Companions - كتاب المناقب',
    'Establishing the Prayer and the Sunnah Regarding Them - كتاب إقامة الصلاة والسنة فيها',
    'Chapters on Recitation - كتاب القراءات عن رسول الله صلى الله عليه وسلم',
    'Blood Money (Ad-Diyat) - كتاب الديات',
    'The Book of Fasting - كتاب الصيام',
    'The Book Pertaining to Punishments Prescribed by Islam - كتاب الحدود',
    'Fasting - كتاب الصوم',
    'The Book of Masaaqah - كتاب المساقاة',
    'Chapters on Medicine - كتاب الطب',
    'Good Manners and Form (Al-Adab) - كتاب الأدب',
    'The Book of Purification - كتاب الطهارة',
    'Chapters on Parables - كتاب الأمثال عن رسول الله صلى الله عليه وسلم',
    'Wishes - كتاب التمنى',
    'The Book of Virtue; Good Manners and Joining of the Ties of Relationship - كتاب البر والصلة والآداب',
    'Prayer (Kitab Al-Salat) - كتاب الصلاة',
    'The Book on Clothing - كتاب اللباس',
    'Chapters On Dreams - كتاب الرؤيا عن رسول الله صلى الله عليه وسلم',
    'The Book of the Kind Treatment of Women - كتاب عشرة النساء',
    'Supporting the Family - كتاب النفقات',
    'Wedlock; Marriage (Nikaah) - كتاب النكاح',
    'The Book on Military Expeditions - كتاب السير عن رسول الله صلى الله عليه وسلم',
    "Retiring to a Mosque for Remembrance of Allah (I'tikaf) - كتاب الاعتكاف",
    'The Book of Luqatah - كتاب اللقطة',
    'Revelation - كتاب بدء الوحى',
    'Interpretation of Dreams - كتاب التعبير',
    'The Book of the Sunnah - كتاب المقدمة',
    "Chapters On Wala' And Gifts - كتاب الولاء والهبة عن رسول الله صلى الله عليه وسلم",
    'Tricks - كتاب الحيل',
    "The Book of al-Bay'ah - كتاب البيعة",
    'The Book of Funerals - كتاب الجنائز',
    'The Book on General Behaviour - كتاب الآداب',
    'Signet-Rings (Kitab Al-Khatam) - كتاب الخاتم',
    'Chapters on the description of Paradise - كتاب صفة الجنة عن رسول الله صلى الله عليه وسلم',
    'The Book on Virtues of Jihad - كتاب فضائل الجهاد عن رسول الله صلى الله عليه وسلم',
    "Chapters on The Virtues of the Qur'an - كتاب فضائل القرآن عن رسول الله صلى الله عليه وسلم",
    'Types of Blood-Wit (Kitab Al-Diyat) - كتاب الديات',
    'Chapters Regarding Funerals - كتاب الجنائز',
    'Fighting for the Cause of Allah (Jihaad) - كتاب الجهاد والسير',
    "The Book of the Prayer for the Two 'Eids - كتاب صلاة العيدين",
    'The Book of the Commencement of the Prayer - كتاب الافتتاح',
    'The Book on Business - كتاب البيوع عن رسول الله صلى الله عليه وسلم',
    'Forgetfulness in Prayer - كتاب السهو',
    'Chapters on Seeking Permission - كتاب الاستئذان والآداب عن رسول الله صلى الله عليه وسلم',
    'Beginning of Creation - كتاب بدء الخلق',
    "Dialects and Readings of the Qur'an (Kitab Al-Huruf Wa Al-Qira'at) - كتاب الحروف والقراءات",
    'Medicine - كتاب الطب',
    'The Book of Manumission of Slaves - كتاب العتق',
    "The Book of Jumu'ah (Friday Prayer) - كتاب الجمعة",
    '`Umrah (Minor pilgrimage) - كتاب العمرة',
    'Divorce (Kitab Al-Talaq) - كتاب الطلاق',
    'Actions while Praying - كتاب العمل فى الصلاة',
    'The Chapters on Jihad - كتاب الجهاد',
    'Fear Prayer - كتاب صلاة الخوف',
    'Bathing (Ghusl) - كتاب الغسل',
    'Wills (Kitab Al-Wasaya) - كتاب الوصايا',
    'The Book of Seeking Refuge with Allah - كتاب الاستعاذة',
    'Knowledge - كتاب العلم',
    'Manumission of Slaves - كتاب العتق',
    'The Book on Blood Money - كتاب الديات عن رسول الله صلى الله عليه وسلم',
    'The Book Pertaining to the Oath; for Establishing the Responsibility of Murders; Fighting; Requital - كتاب القسامة والمحاربين والقصاص والديات',
    'Wills and Testaments (Wasaayaa) - كتاب الوصايا',
    "Ablutions (Wudu') - كتاب الوضوء",
    'The Book of Games and the Animals which May be Slaughtered and the Aninals that Are to be Eaten - كتاب الصيد والذبائح وما يؤكل من الحيوان',
    'Etiquette - كتاب الأدب',
    'The Book on Hajj - كتاب الحج عن رسول الله صلى الله عليه وسلم',
    'The Book of ad-Dahaya (Sacrifices) - كتاب الضحايا',
    'Interpretation of Dreams - كتاب تعبير الرؤيا',
    'The Book Pertaining to the Remembrance of Allah; Supplication; Repentance and Seeking Forgiveness - كتاب الذكر والدعاء والتوبة والاستغفار',
    'Times of the Prayers - كتاب مواقيت الصلاة',
    'Rubbing hands and feet with dust (Tayammum) - كتاب التيمم',
    "Shares of Inheritance (Kitab Al-Fara'id) - كتاب الفرائض",
    'The Chapters on Marriage - كتاب النكاح',
    'Chapters on Hajj Rituals - كتاب المناسك',
    'The Book of Gifts - كتاب الهبة',
    'Invocations - كتاب الدعوات',
    'Distribution of Water - كتاب المساقاة',
    'The Book Pertaining to the Merits of the Companions (Allah Be Pleased With Them) of the Holy Prophet - كتاب فضائل الصحابة رضى الله تعالى عنهم',
    'Chapters On Zuhd - كتاب الزهد عن رسول الله صلى الله عليه وسلم',
    'Chapters on Shares of Inheritance - كتاب الفرائض',
    'The Book on Vows and Oaths - كتاب النذور والأيمان عن رسول الله صلى الله عليه وسلم',
    'The Book of Water - كتاب المياه',
    'The Book Pertaining to Paradise; Its Description; Its Bounties and Its Intimates - كتاب الجنة وصفة نعيمها وأهلها',
    'Kafalah - كتاب الكفالة',
    'The Chapters on Business Transactions - كتاب التجارات',
    'The Book Pertaining to Repentance and Exhortation to Repentance - كتاب التوبة',
    'The Book on Marriage - كتاب النكاح عن رسول الله صلى الله عليه وسلم',
    'The Chapters on Divorce - كتاب الطلاق',
    'The Book of Heart-Melting Traditions - كتاب الرقاق',
    'Divination and Omens (Kitab Al-Kahanah Wa Al-Tatayyur) - كتاب الكهانة و التطير',
    'Detailed Injunctions about Ramadan - كتاب شهر رمضان',
    'The Two Festivals (Eids) - كتاب العيدين',
    "Shuf'a - كتاب الشفعة",
    'Prescribed Punishments (Kitab Al-Hudud) - كتاب الحدود',
    'Sales in which a Price is paid for Goods to be Delivered Later (As-Salam) - كتاب السلم',
    'The Book of Vows - كتاب النذر',
    'Medicine (Kitab Al-Tibb) - كتاب الطب',
    'The Book on Legal Punishments (Al-Hudud) - كتاب الحدود عن رسول الله صلى الله عليه وسلم',
    'The Book of the Qiblah - كتاب القبلة',
    'The Book of Endowments - كتاب الإحباس',
    'The Book Of Faith and its Signs - كتاب الإيمان وشرائعه',
    'Hunting; Slaughtering - كتاب الذبائح والصيد',
    'Commercial Transactions (Kitab Al-Buyu) - كتاب البيوع',
    "Prophetic Commentary on the Qur'an (Tafseer of the Prophet (pbuh)) - كتاب التفسير",
    'The Book of Cutting off the Hand of the Thief - كتاب قطع السارق',
    "Tribute, Spoils, and Rulership (Kitab Al-Kharaj, Wal-Fai' Wal-Imarah) - كتاب الخراج والإمارة والفىء",
    'Chapters on Slaughtering - كتاب الذبائح',
    'Makaatib - كتاب المكاتب',
    'The Chapters on Charity - كتاب الصدقات',
    'Agriculture - كتاب المزارعة',
    'The Book on the Two Eids - أَبْوَابُ الْعِيدَيْنِ عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ',
    'Judgments (Ahkaam) - كتاب الأحكام',
    'The Book Pertaining to Judicial Decisions - كتاب الأقضية',
    'Chapters on Hunting - كتاب الصيد',
    'Drinks - كتاب الأشربة',
    'The Book of Eclipses - كتاب الكسوف',
    'Knowledge (Kitab Al-Ilm) - كتاب العلم',
    'The Chapters on Blood Money - كتاب الديات',
    'The Book of Faith - كتاب الإيمان',
    'Chapters on Knowledge - كتاب العلم عن رسول الله صلى الله عليه وسلم',
    'The Book Pertaining to Clothes and Decoration - كتاب اللباس والزينة',
    "The Book of al-'Aqiqah - كتاب العقيقة",
    'Dress - كتاب اللباس',
    'The Book of Jihad and Expedition - كتاب الجهاد والسير',
    'The Book of the Adhan and the Sunnah Regarding It - كتاب الأذان والسنة فيها',
    'The Book of Bequests - كتاب الوصية',
    'Oaths and Vows (Kitab Al-Aiman Wa Al-Nudhur) - كتاب الأيمان والنذور',
    'The Chapters on Legal Punishments - كتاب الحدود',
    'Partnership - كتاب الشركة',
    "Funerals (Al-Janaa'iz) - كتاب الجنائز",
    'Accepting Information Given by a Truthful Person - كتاب أخبار الآحاد',
    "The Book of 'Umra - كتاب العمرى",
    'Hajj (Pilgrimage) - كتاب الحج',
    'The Book of Menstruation and Istihadah - كتاب الحيض والاستحاضة',
    'The Book of Hajj - كتاب مناسك الحج',
    'Fasting (Kitab Al-Siyam) - كتاب الصوم',
    'Gifts - كتاب الهبة وفضلها والتحريض عليها',
    'The Book on Traveling - أَبْوَابُ السَّفَرِ',
    'Limits and Punishments set by Allah (Hudood) - كتاب الحدود',
    'Divine Will (Al-Qadar) - كتاب القدر',
    'The Book of the Prayer - كتاب الصلاة',
    'The Book Pertaining to Piety and Softening of Hearts - كتاب الزهد والرقائق',
    'Clothing (Kitab Al-Libas) - كتاب اللباس',
    'Detailed Rules of Law about the Prayer during Journey - كتاب صلاة السفر',
    'Oneness; Uniqueness of Allah (Tawheed) - كتاب التوحيد',
    'Patients - كتاب المرضى',
    'The Book of Divorce - كتاب الطلاق',
    'The Book of the Masjids - كتاب المساجد',
    'Prayers (Salat) - كتاب الصلاة',
    'Praying at Night in Ramadaan (Taraweeh) - كتاب صلاة التراويح',
    "Jizyah and Mawaada'ah - كتاب الجزية والموادعة",
    'Afflictions and the End of the World - كتاب الفتن',
    "Foods (Kitab Al-At'imah) - كتاب الأطعمة",
    'Sales and Trade - كتاب البيوع',
    'The Book of Horses, Races and Shooting - كتاب الخيل',
    'The Book on the Day of Friday - كِتَاب الْجُمُعَةِ عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ',
    'The Book of Prayers - كتاب الصلاة',
    'Sacrifice (Kitab Al-Dahaya) - كتاب الضحايا',
    "Holding Fast to the Qur'an and Sunnah - كتاب الاعتصام بالكتاب والسنة",
    'The Book of Jihad - كتاب الجهاد',
    'The Chapters Regarding Zakat - كتاب الزكاة',
    'Loans; Payment of Loans; Freezing of Property; Bankruptcy - كتاب فى الاستقراض',
    'The Book of Forgetfulness (In Prayer) - كتاب السهو',
    "The Book of al-Fara' and al-'Atirah - كتاب الفرع والعتيرة",
    'Battles (Kitab Al-Malahim) - كتاب الملاحم',
    'Oaths and Vows - كتاب الأيمان والنذور',
    'To make the Heart Tender (Ar-Riqaq) - كتاب الرقاق',
    'The Book of the Adhan (The Call to Prayer) - كتاب الأذان',
    'Merits of the Helpers in Madinah (Ansaar) - كتاب مناقب الأنصار',
    'The Chapters on Wills - كتاب الوصايا',
    'The Book on the Description of Hellfire - كتاب صفة جهنم عن رسول الله صلى الله عليه وسلم',
    'Combing the Hair (Kitab Al-Tarajjul) - كتاب الترجل',
    'The Book of Prayer (Friday) - كتاب الجمعة',
    'The Book of the Etiquette of Judges - كتاب آداب القضاة',
    'Shortening the Prayers (At-Taqseer) - كتاب التقصير',
    'Khusoomaat - كتاب الخصومات',
    "Chapters on the description of the Day of Judgement, Ar-Riqaq, and Al-Wara' - كتاب صفة القيامة والرقائق والورع عن رسول الله صلى الله",
    'Chapters On Inheritance - كتاب الفرائض عن رسول الله صلى الله عليه وسلم',
    'The Book of Zakah - كتاب الزكاة',
    'The Promised Deliverer (Kitab Al-Mahdi) - كتاب المهدى',
    'Chapters on Food - كتاب الأطعمة',
    'The Book of Oaths - كتاب الأيمان',
    'Jihad (Kitab Al-Jihad) - كتاب الجهاد',
    'Chapters on Medicine - كتاب الطب عن رسول اللَّهِ صلى الله عليه وسلم',
    'Peacemaking - كتاب الصلح',
    'The Book of Commentary - كتاب التفسير',
    'The Book of Lost and Found Items - كتاب اللقطة',
    "The Book on Divorce and Li'an - كتاب الطلاق واللعان عن رسول الله صلى الله عليه وسلم",
    "Prostration During Recital of Qur'an - كتاب سجود القرآن",
    'The Chapters on Pawning - كتاب الرهون',
    'The Book Giving Description of the Day of Judgement; Paradise and Hell - كتاب صفة القيامة والجنة والنار',
    'Voluntary Prayers - كتاب التطوع',
    'The Book on Salat (Prayer) - كتاب الصلاة',
    'Expiation for Unfulfilled Oaths - كتاب كفارات الأيمان',
    'The Book on Suckling - كتاب الرضاع',
    'The Book on Jihad - كتاب الجهاد عن رسول الله صلى الله عليه وسلم',
    'The Chapters on Gifts - كتاب الهبات',
    'Hiring - كتاب الإجارة',
    'Chapters on Virtues - كتاب المناقب عن رسول الله صلى الله عليه وسلم',
    'The Chapters on Pre-emption - كتاب الشفعة',
    'Companions of the Prophet - كتاب فضائل أصحاب النبى صلى الله عليه وسلم',
    'The Book On The Mosques And The Congregations - كتاب المساجد والجماعات',
    'The Chapters on Expiation - كتاب الكفارات',
    'The Book of Poetry - كتاب الشعر',
    "Funerals (Kitab Al-Jana'iz) - كتاب الجنائز",
    'Drinks (Kitab Al-Ashribah) - كتاب الأشربة',
    'The Book of Qiyam Al-Lail (The Night Prayer) and Voluntary Prayers During the Day - كتاب قيام الليل وتطوع النهار',
    'Dealing with Apostates - كتاب استتابة المرتدين والمعاندين وقتالهم',
    'Witnesses - كتاب الشهادات',
    "Prostration while reciting the Qur'an - كتاب سجود القرآن",
    'General Behavior (Kitab Al-Adab) - كتاب الأدب',
    'Zakat (Kitab Al-Zakat) - كتاب الزكاة',
    'Hot Baths (Kitab Al-Hammam) - كتاب الحمَّام',
    'Introduction - كتاب المقدمة',
    'Wages (Kitab Al-Ijarah) - كتاب الإجارة',
    'The Book of Adornment - كتاب الزينة من السنن',
    'Prophets - كتاب أحاديث الأنبياء',
    'Chapters On Al-Qadar - كتاب القدر عن رسول الله صلى الله عليه وسلم',
    'Punishment of Disbelievers at War with Allah and His Apostle - كتاب المحاربين من أهل الكفر والردة',
    "The Book of Distribution of Al-Fay' - كتاب قسم الفىء",
    'The Book of Mosques and Places of Prayer - كتاب الْمَسَاجِدِ وَمَوَاضِعِ الصَّلاَةِ',
    'The Book of Destiny - كتاب القدر',
    'The Book of Wills - كتاب الوصايا',
    'The Book of ar-Ruqba - كتاب الرقبى',
    'The Book of Oaths and Vows - كتاب الأيمان والنذور',
    'The Book Pertaining to the Excellent Qualities of the Holy Prophet (may Peace be upon them) and His - كتاب الفضائل',
    'The Book of Oaths (qasamah), Retaliation and Blood Money - كتاب القسامة',
    'Virtues of Madinah - كتاب فضائل المدينة',
    'The Book of Prayer (Rain) - كتاب صلاة الاستسقاء\u200f',
    'The Chapters on Lost Property - كتاب اللقطة',
    'Asking Permission - كتاب الاستئذان',
    'Transferance of a Debt from One Person to Another (Al-Hawaala) - كتاب الحوالات',
    'Saying Something under Compulsion (Ikraah) - كتاب الإكراه',
    'The Book of Zakat - كتاب الزكاة',
    'Invoking Allah for Rain (Istisqaa) - كتاب الاستسقاء',
    'The Book of Pilgrimage - كتاب الحج',
    'The Book of Menstruation - كتاب الحيض',
    "The Book of Praying for Rain (Al-Istisqa') - كتاب الاستسقاء",
    'Pilgrims Prevented from Completing the Pilgrimage - كتاب المحصر',
    'Chapters on Drinks - كتاب الأشربة',
    'The Book on Al-Witr - أَبْوَابُ الْوِتْرِ',
    'The Book of Presents - كتاب النحل',
    'Chapters On Al-Fitan - كتاب الفتن عن رسول الله صلى الله عليه وسلم',
    'Chapters on Righteousness And Maintaining Good Relations With Relatives - كتاب البر والصلة عن رسول الله صلى الله عليه وسلم',
    'The Book on Salutations and Greetings - كتاب السلام',
    "The Book of The At-Tatbiq (Clasping One's Hands Together) - كتاب التطبيق",
    'The Book of Knowledge - كتاب العلم',
    'The Book of Prayer (Travellers) - كتاب صلاة المسافرين وقصرها',
    'The Book of the Times (of Prayer) - كتاب المواقيت',
    'Model Behavior of the Prophet (Kitab Al-Sunnah) - كتاب السنة',
    'Conditions - كتاب الشروط',
    'Lost Things Picked up by Someone (Luqatah) - كتاب فى اللقطة',
    'The Book of Hunting and Slaughtering - كتاب الصيد والذبائح',
    'Marriage (Kitab Al-Nikah) - كتاب النكاح',
    'The Book of Leading the Prayer (Al-Imamah) - كتاب الإمامة',
    'The Chapters on Manumission (of Slaves) - كتاب العتق',
    'Food; Meals - كتاب الأطعمة',
    "Virtues of the Qur'an - كتاب فضائل القرآن",
    'The Book of Prayer (Eclipse) - كتاب الكسوف',
    'Tribulations - كتاب الفتن',
    'Prayer at Night (Tahajjud) - كتاب التهجد',
    'Detailed Injunctions about Witr - كتاب الوتر',
    'Chapters on Manners - كتاب الأدب عن رسول الله صلى الله عليه وسلم',
    'Trials and Fierce Battles (Kitab Al-Fitan Wa Al-Malahim) - كتاب الفتن والملاحم',
    'The Chapters on Rulings - كتاب الأحكام',
    'The Book on Faith - كتاب الإيمان عن رسول الله صلى الله عليه وسلم',
    'The Book of Sacrifices - كتاب الأضاحى',
    'Friday Prayer - كتاب الجمعة',
    'Chapters On Wasaya (Wills and Testament) - كتاب الوصايا عن رسول الله صلى الله عليه وسلم',
    'The Office of the Judge (Kitab Al-Aqdiyah) - كتاب الأقضية',
    'The Book on Drinks - كتاب الأشربة عن رسول الله صلى الله عليه وسلم',
    'Menstrual Periods - كتاب الحيض',
    'The Book on Hunting - كتاب الصيد والذبائح عن رسول الله صلى الله عليه وسلم',
    'Chapters on Supplication - كتاب الدعوات عن رسول الله صلى الله عليه وسلم',
    'Representation; Authorization; Business by Proxy - كتاب الوكالة',
    'Fasting - كتاب الصيام',
    'The Book on Food - كتاب الأطعمة عن رسول الله صلى الله عليه وسلم',
    'The Book on Government - كتاب الإمارة',
    'Pertaining To The Charateristics Of The Hypocrites And Command Concerning Them - كتاب صفات المنافقين وأحكامهم',
    'Oppressions - كتاب المظالم',
    'Chapters on Dress - كتاب اللباس',
    'The Book on Zakat - كتاب الزكاة عن رسول الله صلى الله عليه وسلم',
    'Purification (Kitab Al-Taharah) - كتاب الطهارة',
    'The Book of Purification and its Sunnah - كتاب الطهارة وسننها',
    'The Book of Transactions - كتاب البيوع',
    'The Chapters On Judgements From The Messenger of Allah - كتاب الأحكام عن رسول الله صلى الله عليه وسلم',
    'Eclipses - كتاب الكسوف',
    'Chapters on Sacrifices - كتاب الأضاحي',
    'The Book of Emancipating Slaves - كتاب العتق',
    "The Rites of Hajj (Kitab Al-Manasik Wa'l-Hajj) - كتاب المناسك",
    'Military Expeditions led by the Prophet (pbuh) (Al-Maghaazi) - كتاب المغازى',
    'Sacrifice on Occasion of Birth (`Aqiqa) - كتاب العقيقة',
    'The Book of Prayer (Two Eids) - كتاب صلاة العيدين',
    'The Book of Fighting [The Prohibition of Bloodshed] - كتاب تحريم الدم',
    'The Book of Suckling - كتاب الرضاع',
    "The Book on Jana''iz (Funerals) - كتاب الجنائز عن رسول الله صلى الله عليه وسلم",
    'Chapters On Witnesses - كتاب الشهادات عن رسول الله صلى الله عليه وسلم',
    'The Book of Financial Transactions - كتاب البيوع',
    'Call to Prayers (Adhaan) - كتاب الأذان',
    'The Book Concerning the Use of Correct Words - كتاب الألفاظ من الأدب وغيرها',
    'The Book of Vision - كتاب الرؤيا',
    'One-fifth of Booty to the Cause of Allah (Khumus) - كتاب فرض الخمس',
    'Game (Kitab Al-Said) - كتاب الصيد',
    'The Book of Drinks - كتاب الأشربة',
    'The Book of Salah - كتاب الصلاة',
    'Al-Adha Festival Sacrifice (Adaahi) - كتاب الأضاحي',
    'The Book of the Fear Prayer - كتاب صلاة الخوف',
    'The Book on Fasting - كتاب الصوم عن رسول الله صلى الله عليه وسلم',
    'The Book of Shortening the Prayer When Traveling - كتاب تقصير الصلاة فى السفر',
    'Mortgaging - كتاب الرهن',
    'The Book of Marriage - كتاب النكاح',
    'The Book of Gifts - كتاب الهبات',
    'The Book on Purification - كتاب الطهارة عن رسول الله صلى الله عليه وسلم',
    'Virtues of the Night of Qadr - كتاب فضل ليلة القدر',
    'The Book of Prayer (Funerals) - كتاب الجنائز',
    'Divorce - كتاب الطلاق',
    "The Book of I'tikaf - كتاب الاعتكاف",
    'Supplication - كتاب الدعاء',
    'The Book of Ghusl and Tayammum - كتاب الغسل والتيمم',
    "The Book Of The Prayer For Rain (Kitab al-Istisqa') - كتاب الاستسقاء",
    'Obligatory Charity Tax (Zakat) - كتاب الزكاة',
    'Penalty of Hunting while on Pilgrimage - كتاب جزاء الصيد',
    'Witr Prayer - كتاب الوتر',
    'The Book of Invoking Curses - كتاب اللعان',
    'Chapters on Tafsir - كتاب تفسير القرآن عن رسول الله صلى الله عليه وسلم',
    "Laws of Inheritance (Al-Faraa'id) - كتاب الفرائض"
  ];
  static const List arabicHeads = [
    'كتاب الإيمان',
    'كتاب فضل الصلاة فى مسجد مكة والمدينة',
    'كتاب الفرائض',
    'كتاب الأضاحى عن رسول الله صلى الله عليه وسلم',
    'كتاب الفتن وأشراط الساعة',
    '    - كتاب المناقب',
    'كتاب إقامة الصلاة والسنة فيها',
    'كتاب القراءات عن رسول الله صلى الله عليه وسلم',
    'كتاب الديات',
    'كتاب الصيام',
    'كتاب الحدود',
    'كتاب الصوم',
    'كتاب المساقاة',
    'كتاب الطب',
    'كتاب الأدب',
    'كتاب الطهارة',
    'كتاب الأمثال عن رسول الله صلى الله عليه وسلم',
    'كتاب التمنى',
    'كتاب البر والصلة والآداب',
    'كتاب الصلاة',
    'كتاب اللباس',
    'كتاب الرؤيا عن رسول الله صلى الله عليه وسلم',
    'كتاب عشرة النساء',
    'كتاب النفقات',
    'كتاب النكاح',
    'كتاب السير عن رسول الله صلى الله عليه وسلم',
    'كتاب الاعتكاف',
    'كتاب اللقطة',
    'كتاب بدء الوحى',
    'كتاب التعبير',
    'كتاب المقدمة',
    '  - كتاب الولاء والهبة عن رسول الله صلى الله عليه وسلم',
    'كتاب الحيل',
    ' - كتاب البيعة',
    'كتاب الجنائز',
    'كتاب الآداب',
    'كتاب الخاتم',
    'كتاب صفة الجنة عن رسول الله صلى الله عليه وسلم',
    'كتاب فضائل الجهاد عن رسول الله صلى الله عليه وسلم',
    '- كتاب فضائل القرآن عن رسول الله صلى الله عليه وسلم',
    'كتاب الديات',
    'كتاب الجنائز',
    ' - كتاب الجهاد والسير',
    '- كتاب صلاة العيدين',
    'كتاب الافتتاح',
    'كتاب البيوع عن رسول الله صلى الله عليه وسلم',
    'كتاب السهو',
    'كتاب الاستئذان والآداب عن رسول الله صلى الله عليه وسلم',
    'كتاب بدء الخلق',
    "كتاب الحروف والقراءات",
    'كتاب الطب',
    'كتاب العتق',
    'كتاب الجمعة',
    'كتاب العمرة',
    'كتاب الطلاق',
    'كتاب العمل فى الصلاة',
    'كتاب الجهاد',
    'كتاب صلاة الخوف',
    '  كتاب الغسل',
    'كتاب الوصايا',
    'كتاب الاستعاذة',
    'كتاب العلم',
    'كتاب العتق',
    'كتاب الديات عن رسول الله صلى الله عليه وسلم',
    'كتاب القسامة والمحاربين والقصاص والديات',
    '  كتاب الوصايا',
    'كتاب الوضوء',
    'كتاب الصيد والذبائح وما يؤكل من الحيوان',
    'كتاب الأدب',
    'كتاب الحج عن رسول الله صلى الله عليه وسلم',
    ' كتاب الضحايا',
    'كتاب تعبير الرؤيا',
    ' كتاب الذكر والدعاء والتوبة والاستغفار',
    'كتاب مواقيت الصلاة',
    ' - كتاب التيمم',
    " كتاب الفرائض",
    'كتاب النكاح',
    'كتاب المناسك',
    'كتاب الهبة',
    'كتاب الدعوات',
    'كتاب المساقاة',
    ' كتاب فضائل الصحابة رضى الله تعالى عنهم',
    'كتاب الزهد عن رسول الله صلى الله عليه وسلم',
    'كتاب الفرائض',
    'كتاب النذور والأيمان عن رسول الله صلى الله عليه وسلم',
    'كتاب المياه',
    'كتاب الجنة وصفة نعيمها وأهلها',
    'كتاب الكفالة',
    'كتاب التجارات',
    'كتاب التوبة',
    'كتاب النكاح عن رسول الله صلى الله عليه وسلم',
    'كتاب الطلاق',
    '  كتاب الرقاق',
    ' كتاب الكهانة و التطير',
    'كتاب شهر رمضان',
    '  كتاب العيدين',
    'كتاب الشفعة',
    'كتاب الحدود',
    'كتاب السلم',
    'كتاب النذر',
    ' كتاب الطب',
    'كتاب الحدود عن رسول الله صلى الله عليه وسلم',
    'كتاب القبلة',
    'كتاب الإحباس',
    'كتاب الإيمان وشرائعه',
    ' كتاب الذبائح والصيد',
    'كتاب البيوع',
    ' كتاب التفسير',
    'كتاب قطع السارق',
    " كتاب الخراج والإمارة والفىء",
    'كتاب الذبائح',
    'كتاب المكاتب',
    'كتاب الصدقات',
    'كتاب المزارعة',
    'أَبْوَابُ الْعِيدَيْنِ عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ',
    ' - كتاب الأحكام',
    'كتاب الأقضية',
    'كتاب الصيد',
    'كتاب الأشربة',
    'كتاب الكسوف',
    ' كتاب العلم',
    'كتاب الديات',
    'كتاب الإيمان',
    'كتاب العلم عن رسول الله صلى الله عليه وسلم',
    'كتاب اللباس والزينة',
    ' كتاب العقيقة',
    'كتاب اللباس',
    'كتاب الجهاد والسير',
    'كتاب الأذان والسنة فيها',
    'كتاب الوصية',
    'كتاب الأيمان والنذور',
    'كتاب الحدود',
    'كتاب الشركة',
    "كتاب الجنائز",
    'كتاب أخبار الآحاد',
    '- كتاب العمرى',
    ' - كتاب الحج',
    'كتاب الحيض والاستحاضة',
    'كتاب مناسك الحج',
    ' كتاب الصوم',
    'كتاب الهبة وفضلها والتحريض عليها',
    'أَبْوَابُ السَّفَرِ',
    ' كتاب الحدود',
    ' كتاب القدر',
    'كتاب الصلاة',
    'كتاب الزهد والرقائق',
    'كتاب اللباس',
    'كتاب صلاة السفر',
    'كتاب التوحيد',
    'كتاب المرضى',
    'كتاب الطلاق',
    'كتاب المساجد',
    '  كتاب الصلاة',
    ' كتاب صلاة التراويح',
    'كتاب الجزية والموادعة',
    'كتاب الفتن',
    " كتاب الأطعمة",
    'كتاب البيوع',
    '  كتاب الخيل',
    'كِتَاب الْجُمُعَةِ عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ',
    'كتاب الصلاة',
    'كتاب الضحايا',
    '  كتاب الاعتصام بالكتاب والسنة',
    'كتاب الجهاد',
    'كتاب الزكاة',
    ' كتاب فى الاستقراض',
    ' السهو',
    " كتاب الفرع والعتيرة",
    'كتاب الملاحم',
    'كتاب الأيمان والنذور',
    'كتاب الرقاق',
    'كتاب الأذان',
    'كتاب مناقب الأنصار',
    'كتاب الوصايا',
    'كتاب صفة جهنم عن رسول الله صلى الله عليه وسلم',
    'كتاب الترجل',
    ' - كتاب الجمعة',
    'كتاب آداب القضاة',
    'كتاب التقصير',
    'كتاب الخصومات',
    " كتاب صفة القيامة والرقائق والورع عن رسول الله صلى الله",
    'كتاب الفرائض عن رسول الله صلى الله عليه وسلم',
    'كتاب الزكاة',
    ' كتاب المهدى',
    'كتاب الأطعمة',
    'كتاب الأيمان',
    'كتاب الجهاد',
    'كتاب الطب عن رسول اللَّهِ صلى الله عليه وسلم',
    'كتاب الصلح',
    'كتاب التفسير',
    'كتاب اللقطة',
    'كتاب الطلاق واللعان عن رسول الله صلى الله عليه وسلم',
    ' كتاب سجود القرآن',
    'كتاب الرهون',
    'كتاب صفة القيامة والجنة والنار',
    'كتاب التطوع',
    'كتاب الصلاة',
    'كتاب كفارات الأيمان',
    'كتاب الرضاع',
    'كتاب الجهاد عن رسول الله صلى الله عليه وسلم',
    'كتاب الهبات',
    'كتاب الإجارة',
    'كتاب المناقب عن رسول الله صلى الله عليه وسلم',
    '- كتاب الشفعة',
    'كتاب فضائل أصحاب النبى صلى الله عليه وسلم',
    'كتاب المساجد والجماعات',
    'كتاب الكفارات',
    'كتاب الشعر',
    "كتاب الجنائز",
    'كتاب الأشربة',
    'كتاب قيام الليل وتطوع النهار',
    'كتاب استتابة المرتدين والمعاندين وقتالهم',
    'كتاب الشهادات',
    '- كتاب سجود القرآن',
    'كتاب الأدب',
    ' كتاب الزكاة',
    'كتاب الحمَّام',
    'كتاب المقدمة',
    ' كتاب الإجارة',
    'كتاب الزينة من السنن',
    'كتاب أحاديث الأنبياء',
    '- كتاب القدر عن رسول الله صلى الله عليه وسلم',
    'كتاب المحاربين من أهل الكفر والردة',
    '  كتاب قسم الفىء',
    'كتاب الْمَسَاجِدِ وَمَوَاضِعِ الصَّلاَةِ',
    'كتاب القدر',
    'كتاب الوصايا',
    'كتاب الرقبى',
    'كتاب الأيمان والنذور',
    ' كتاب الفضائل',
    ' كتاب القسامة',
    'كتاب فضائل المدينة',
    ' كتاب صلاة الاستسقاء\u200f',
    'كتاب اللقطة',
    'كتاب الاستئذان',
    'كتاب الحوالات',
    ' كتاب الإكراه',
    'كتاب الزكاة',
    'كتاب الاستسقاء',
    'كتاب الحج',
    'كتاب الحيض',
    "'كتاب الاستسقاء",
    'كتاب المحصر',
    'كتاب الأشربة',
    '- أَبْوَابُ الْوِتْرِ',
    'كتاب النحل',
    '- كتاب الفتن عن رسول الله صلى الله عليه وسلم',
    'كتاب البر والصلة عن رسول الله صلى الله عليه وسلم',
    'كتاب السلام',
    "كتاب التطبيق",
    'كتاب العلم',
    'كتاب صلاة المسافرين وقصرها',
    'كتاب المواقيت',
    ' كتاب السنة',
    'كتاب الشروط',
    'كتاب فى اللقطة',
    'كتاب الصيد والذبائح',
    'كتاب النكاح',
    ' كتاب الإمامة',
    ' كتاب العتق',
    '  كتاب الأطعمة',
    ' كتاب فضائل القرآن',
    'كتاب الكسوف',
    'كتاب الفتن',
    ' كتاب التهجد',
    'كتاب الوتر',
    'كتاب الأدب عن رسول الله صلى الله عليه وسلم',
    'كتاب الفتن والملاحم',
    'كتاب الأحكام',
    'كتاب الإيمان عن رسول الله صلى الله عليه وسلم',
    'كتاب الأضاحى',
    'كتاب الجمعة',
    'كتاب الوصايا عن رسول الله صلى الله عليه وسلم',
    'كتاب الأقضية',
    'كتاب الأشربة عن رسول الله صلى الله عليه وسلم',
    'كتاب الحيض',
    'كتاب الصيد والذبائح عن رسول الله صلى الله عليه وسلم',
    'كتاب الدعوات عن رسول الله صلى الله عليه وسلم',
    'كتاب الوكالة',
    'كتاب الصيام',
    'كتاب الأطعمة عن رسول الله صلى الله عليه وسلم',
    'كتاب الإمارة',
    'كتاب صفات المنافقين وأحكامهم',
    'كتاب المظالم',
    'كتاب اللباس',
    'كتاب الزكاة عن رسول الله صلى الله عليه وسلم',
    'كتاب الطهارة',
    'كتاب الطهارة وسننها',
    'كتاب البيوع',
    'كتاب الأحكام عن رسول الله صلى الله عليه وسلم',
    'كتاب الكسوف',
    'كتاب الأضاحي',
    'كتاب العتق',
    "كتاب المناسك",
    'كتاب المغازى',
    'كتاب العقيقة',
    'كتاب صلاة العيدين',
    'كتاب تحريم الدم',
    'كتاب الرضاع',
    'كتاب الجنائز عن رسول الله صلى الله عليه وسلم',
    'كتاب الشهادات عن رسول الله صلى الله عليه وسلم',
    'كتاب البيوع',
    'كتاب الأذان',
    'كتاب الألفاظ من الأدب وغيرها',
    'كتاب الرؤيا',
    'كتاب فرض الخمس',
    'كتاب الصيد',
    'كتاب الأشربة',
    'كتاب الصلاة',
    'كتاب الأضاحي',
    'كتاب صلاة الخوف',
    'كتاب الصوم عن رسول الله صلى الله عليه وسلم',
    'كتاب تقصير الصلاة فى السفر',
    'كتاب الرهن',
    'كتاب النكاح',
    'كتاب الهبات',
    'كتاب الطهارة عن رسول الله صلى الله عليه وسلم',
    'كتاب فضل ليلة القدر',
    'كتاب الجنائز',
    'كتاب الطلاق',
    'كتاب الاعتكاف',
    'كتاب الدعاء',
    'كتاب الغسل والتيمم',
    "كتاب الاستسقاء",
    ' - كتاب الزكاة',
    'كتاب جزاء الصيد',
    'كتاب الوتر',
    'كتاب اللعان',
    'كتاب تفسير القرآن عن رسول الله صلى الله عليه وسلم',
    "كتاب الفرائض"
  ];
  static const List englishHeads = [
    'Belief',
    'VirtuesofPrayeratMasjidMakkahandMadinah',
    'TheBookPertainingtotheRulesofInheritance',
    'TheBookonSacrifices',
    'TheBookPertainingtotheTurmoilandPortentsoftheLastHour',
    'VirtuesandMeritsoftheProphetpbuhandhisCompanions',
    'EstablishingthePrayerandtheSunnahRegardingThem',
    'ChaptersonRecitation',
    'BloodMoneyAdDiyat',
    'TheBookofFasting',
    'TheBookPertainingtoPunishmentsPrescribedbyIslam',
    'Fasting',
    'TheBookofMasaaqah',
    'ChaptersonMedicine',
    'GoodMannersandFormAlAdab',
    'TheBookofPurification',
    'ChaptersonParables',
    'Wishes',
    'TheBookofVirtueGoodMannersandJoiningoftheTiesofRelationship',
    'PrayerKitabAlSalat',
    'TheBookonClothing',
    'ChaptersOnDreams',
    'TheBookoftheKindTreatmentofWomen',
    'SupportingtheFamily',
    'WedlockMarriageNikaah',
    'TheBookonMilitaryExpeditions',
    'RetiringtoaMosqueforRemembranceofAllahItikaf',
    'TheBookofLuqatah',
    'Revelation',
    'InterpretationofDreams',
    'TheBookoftheSunnah',
    'ChaptersOnWalaAndGifts',
    'Tricks',
    'TheBookofalBayah',
    'TheBookofFunerals',
    'TheBookonGeneralBehaviour',
    'SignetRingsKitabAlKhatam',
    'ChaptersonthedescriptionofParadise',
    'TheBookonVirtuesofJihad',
    'ChaptersonTheVirtuesoftheQuran',
    'TypesofBloodWitKitabAlDiyat',
    'ChaptersRegardingFunerals',
    'FightingfortheCauseofAllahJihaad',
    'TheBookofthePrayerfortheTwoEids',
    'TheBookoftheCommencementofthePrayer',
    'TheBookonBusiness',
    'ForgetfulnessinPrayer',
    'ChaptersonSeekingPermission',
    'BeginningofCreation',
    'DialectsandReadingsoftheQuranKitabAlHurufWaAlQiraat',
    'Medicine',
    'TheBookofManumissionofSlaves',
    'TheBookofJumuahFridayPrayer',
    'UmrahMinorpilgrimage',
    'DivorceKitabAlTalaq',
    'ActionswhilePraying',
    'TheChaptersonJihad',
    'FearPrayer',
    'BathingGhusl',
    'WillsKitabAlWasaya',
    'TheBookofSeekingRefugewithAllah',
    'Knowledge',
    'ManumissionofSlaves',
    'TheBookonBloodMoney',
    'TheBookPertainingtotheOathforEstablishingtheResponsibilityofMurdersFightingRequital',
    'WillsandTestamentsWasaayaa',
    'AblutionsWudu',
    'TheBookofGamesandtheAnimalswhichMaybeSlaughteredandtheAninalsthatAretobeEaten',
    'Etiquette',
    'TheBookonHajj',
    'TheBookofadDahayaSacrifices',
    'InterpretationofDreams',
    'TheBookPertainingtotheRemembranceofAllahSupplicationRepentanceandSeekingForgiveness',
    'TimesofthePrayers',
    'RubbinghandsandfeetwithdustTayammum',
    'SharesofInheritanceKitabAlFaraid',
    'TheChaptersonMarriage',
    'ChaptersonHajjRituals',
    'TheBookofGifts',
    'Invocations',
    'DistributionofWater',
    'TheBookPertainingtotheMeritsoftheCompanionsAllahBePleasedWithThemoftheHolyProphet',
    'ChaptersOnZuhd',
    'ChaptersonSharesofInheritance',
    'TheBookonVowsandOaths',
    'TheBookofWater',
    'TheBookPertainingtoParadiseItsDescriptionItsBountiesandItsIntimates',
    'Kafalah',
    'TheChaptersonBusinessTransactions',
    'TheBookPertainingtoRepentanceandExhortationtoRepentance',
    'TheBookonMarriage',
    'TheChaptersonDivorce',
    'TheBookofHeartMeltingTraditions',
    'DivinationandOmensKitabAlKahanahWaAlTatayyur',
    'DetailedInjunctionsaboutRamadan',
    'TheTwoFestivalsEids',
    'Shufa',
    'PrescribedPunishmentsKitabAlHudud',
    'SalesinwhichaPriceispaidforGoodstobeDeliveredLaterAsSalam',
    'TheBookofVows',
    'MedicineKitabAlTibb',
    'TheBookonLegalPunishmentsAlHudud',
    'TheBookoftheQiblah',
    'TheBookofEndowments',
    'TheBookOfFaithanditsSigns',
    'HuntingSlaughtering',
    'CommercialTransactionsKitabAlBuyu',
    'PropheticCommentaryontheQuranTafseeroftheProphetpbuh',
    'TheBookofCuttingofftheHandoftheThief',
    'TributeSpoilsandRulershipKitabAlKharajWalFaiWalImarah',
    'ChaptersonSlaughtering',
    'Makaatib',
    'TheChaptersonCharity',
    'Agriculture',
    'TheBookontheTwoEids',
    'JudgmentsAhkaam',
    'TheBookPertainingtoJudicialDecisions',
    'ChaptersonHunting',
    'Drinks',
    'TheBookofEclipses',
    'KnowledgeKitabAlIlm',
    'TheChaptersonBloodMoney',
    'TheBookofFaith',
    'ChaptersonKnowledge',
    'TheBookPertainingtoClothesandDecoration',
    'TheBookofalAqiqah',
    'Dress',
    'TheBookofJihadandExpedition',
    'TheBookoftheAdhanandtheSunnahRegardingIt',
    'TheBookofBequests',
    'OathsandVowsKitabAlAimanWaAlNudhur',
    'TheChaptersonLegalPunishments',
    'Partnership',
    'FuneralsAlJanaaiz',
    'AcceptingInformationGivenbyaTruthfulPerson',
    'TheBookofUmra',
    'HajjPilgrimage',
    'TheBookofMenstruationandIstihadah',
    'TheBookofHajj',
    'FastingKitabAlSiyam',
    'Gifts',
    'TheBookonTraveling',
    'LimitsandPunishmentssetbyAllahHudood',
    'DivineWillAlQadar',
    'TheBookofthePrayer',
    'TheBookPertainingtoPietyandSofteningofHearts',
    'ClothingKitabAlLibas',
    'DetailedRulesofLawaboutthePrayerduringJourney',
    'OnenessUniquenessofAllahTawheed',
    'Patients',
    'TheBookofDivorce',
    'TheBookoftheMasjids',
    'PrayersSalat',
    'PrayingatNightinRamadaanTaraweeh',
    'JizyahandMawaadaah',
    'AfflictionsandtheEndoftheWorld',
    'FoodsKitabAlAtimah',
    'SalesandTrade',
    'TheBookofHorsesRacesandShooting',
    'TheBookontheDayofFriday',
    'TheBookofPrayers',
    'SacrificeKitabAlDahaya',
    'HoldingFasttotheQuranandSunnah',
    'TheBookofJihad',
    'TheChaptersRegardingZakat',
    'LoansPaymentofLoansFreezingofPropertyBankruptcy',
    'TheBookofForgetfulnessInPrayer',
    'TheBookofalFaraandalAtirah',
    'BattlesKitabAlMalahim',
    'OathsandVows',
    'TomaketheHeartTenderArRiqaq',
    'TheBookoftheAdhanTheCalltoPrayer',
    'MeritsoftheHelpersinMadinahAnsaar',
    'TheChaptersonWills',
    'TheBookontheDescriptionofHellfire',
    'CombingtheHairKitabAlTarajjul',
    'TheBookofPrayerFriday',
    'TheBookoftheEtiquetteofJudges',
    'ShorteningthePrayersAtTaqseer',
    'Khusoomaat',
    'ChaptersonthedescriptionoftheDayofJudgementArRiqaqandAlWara',
    'ChaptersOnInheritance',
    'TheBookofZakah',
    'ThePromisedDelivererKitabAlMahdi',
    'ChaptersonFood',
    'TheBookofOaths',
    'JihadKitabAlJihad',
    'ChaptersonMedicine',
    'Peacemaking',
    'TheBookofCommentary',
    'TheBookofLostandFoundItems',
    'TheBookonDivorceandLian',
    'ProstrationDuringRecitalofQuran',
    'TheChaptersonPawning',
    'TheBookGivingDescriptionoftheDayofJudgementParadiseandHell',
    'VoluntaryPrayers',
    'TheBookonSalatPrayer',
    'ExpiationforUnfulfilledOaths',
    'TheBookonSuckling',
    'TheBookonJihad',
    'TheChaptersonGifts',
    'Hiring',
    'ChaptersonVirtues',
    'TheChaptersonPreemption',
    'CompanionsoftheProphet',
    'TheBookOnTheMosquesAndTheCongregations',
    'TheChaptersonExpiation',
    'TheBookofPoetry',
    'FuneralsKitabAlJanaiz',
    'DrinksKitabAlAshribah',
    'TheBookofQiyamAlLailTheNightPrayerandVoluntaryPrayersDuringtheDay',
    'DealingwithApostates',
    'Witnesses',
    'ProstrationwhilerecitingtheQuran',
    'GeneralBehaviorKitabAlAdab',
    'ZakatKitabAlZakat',
    'HotBathsKitabAlHammam',
    'Introduction',
    'WagesKitabAlIjarah',
    'TheBookofAdornment',
    'Prophets',
    'ChaptersOnAlQadar',
    'PunishmentofDisbelieversatWarwithAllahandHisApostle',
    'TheBookofDistributionofAlFay',
    'TheBookofMosquesandPlacesofPrayer',
    'TheBookofDestiny',
    'TheBookofWills',
    'TheBookofarRuqba',
    'TheBookofOathsandVows',
    'TheBookPertainingtotheExcellentQualitiesoftheHolyProphetmayPeacebeuponthemandHis',
    'TheBookofOathsqasamahRetaliationandBloodMoney',
    'VirtuesofMadinah',
    'TheBookofPrayerRain',
    'TheChaptersonLostProperty',
    'AskingPermission',
    'TransferanceofaDebtfromOnePersontoAnotherAlHawaala',
    'SayingSomethingunderCompulsionIkraah',
    'TheBookofZakat',
    'InvokingAllahforRainIstisqaa',
    'TheBookofPilgrimage',
    'TheBookofMenstruation',
    'TheBookofPrayingforRainAlIstisqa',
    'PilgrimsPreventedfromCompletingthePilgrimage',
    'ChaptersonDrinks',
    'TheBookonAlWitr',
    'TheBookofPresents',
    'ChaptersOnAlFitan',
    'ChaptersonRighteousnessAndMaintainingGoodRelationsWithRelatives',
    'TheBookonSalutationsandGreetings',
    'TheBookofTheAtTatbiqClaspingOnesHandsTogether',
    'TheBookofKnowledge',
    'TheBookofPrayerTravellers',
    'TheBookoftheTimesofPrayer',
    'ModelBehavioroftheProphetKitabAlSunnah',
    'Conditions',
    'LostThingsPickedupbySomeoneLuqatah',
    'TheBookofHuntingandSlaughtering',
    'MarriageKitabAlNikah',
    'TheBookofLeadingthePrayerAlImamah',
    'TheChaptersonManumissionofSlaves',
    'FoodMeals',
    'VirtuesoftheQuran',
    'TheBookofPrayerEclipse',
    'Tribulations',
    'PrayeratNightTahajjud',
    'DetailedInjunctionsaboutWitr',
    'ChaptersonManners',
    'TrialsandFierceBattlesKitabAlFitanWaAlMalahim',
    'TheChaptersonRulings',
    'TheBookonFaith',
    'TheBookofSacrifices',
    'FridayPrayer',
    'ChaptersOnWasayaWillsandTestament',
    'TheOfficeoftheJudgeKitabAlAqdiyah',
    'TheBookonDrinks',
    'MenstrualPeriods',
    'TheBookonHunting',
    'ChaptersonSupplication',
    'RepresentationAuthorizationBusinessbyProxy',
    'Fasting',
    'TheBookonFood',
    'TheBookonGovernment',
    'PertainingToTheCharateristicsOfTheHypocritesAndCommandConcerningThem',
    'Oppressions',
    'ChaptersonDress',
    'TheBookonZakat',
    'PurificationKitabAlTaharah',
    'TheBookofPurificationanditsSunnah',
    'TheBookofTransactions',
    'TheChaptersOnJudgementsFromTheMessengerofAllah',
    'Eclipses',
    'ChaptersonSacrifices',
    'TheBookofEmancipatingSlaves',
    'TheRitesofHajjKitabAlManasikWalHajj',
    'MilitaryExpeditionsledbytheProphetpbuhAlMaghaazi',
    'SacrificeonOccasionofBirthAqiqa',
    'TheBookofPrayerTwoEids',
    'TheBookofFightingTheProhibitionofBloodshed',
    'TheBookofSuckling',
    'TheBookonJanaizFunerals',
    'ChaptersOnWitnesses',
    'TheBookofFinancialTransactions',
    'CalltoPrayersAdhaan',
    'TheBookConcerningtheUseofCorrectWords',
    'TheBookofVision',
    'OnefifthofBootytotheCauseofAllahKhumus',
    'GameKitabAlSaid',
    'TheBookofDrinks',
    'TheBookofSalah',
    'AlAdhaFestivalSacrificeAdaahi',
    'TheBookoftheFearPrayer',
    'TheBookonFasting',
    'TheBookofShorteningthePrayerWhenTraveling',
    'Mortgaging',
    'TheBookofMarriage',
    'TheBookofGifts',
    'TheBookonPurification',
    'VirtuesoftheNightofQadr',
    'TheBookofPrayerFunerals',
    'Divorce',
    'TheBookofItikaf',
    'Supplication',
    'TheBookofGhuslandTayammum',
    'TheBookOfThePrayerForRainKitabalIstisqa',
    'ObligatoryCharityTaxZakat',
    'PenaltyofHuntingwhileonPilgrimage',
    'WitrPrayer',
    'TheBookofInvokingCurses',
    'ChaptersonTafsir',
    'LawsofInheritanceAlFaraaid'
  ];
}